import * as KEYS from "./constants"

const KeyMapper = new Map()

KeyMapper.set(65, KEYS.KEY_A)
KeyMapper.set(66, KEYS.KEY_B)
KeyMapper.set(67, KEYS.KEY_C)
KeyMapper.set(68, KEYS.KEY_D)
KeyMapper.set(69, KEYS.KEY_E)
KeyMapper.set(70, KEYS.KEY_F)
KeyMapper.set(71, KEYS.KEY_G)
KeyMapper.set(72, KEYS.KEY_H)
KeyMapper.set(73, KEYS.KEY_I)
KeyMapper.set(74, KEYS.KEY_J)
KeyMapper.set(75, KEYS.KEY_K)
KeyMapper.set(76, KEYS.KEY_L)
KeyMapper.set(77, KEYS.KEY_M)
KeyMapper.set(78, KEYS.KEY_N)
KeyMapper.set(79, KEYS.KEY_O)
KeyMapper.set(80, KEYS.KEY_P)
KeyMapper.set(81, KEYS.KEY_Q)
KeyMapper.set(82, KEYS.KEY_R)
KeyMapper.set(83, KEYS.KEY_S)
KeyMapper.set(84, KEYS.KEY_T)
KeyMapper.set(85, KEYS.KEY_U)
KeyMapper.set(86, KEYS.KEY_V)
KeyMapper.set(87, KEYS.KEY_W)
KeyMapper.set(88, KEYS.KEY_X)
KeyMapper.set(89, KEYS.KEY_Y)
KeyMapper.set(90, KEYS.KEY_Z)

KeyMapper.set(48, KEYS.KEY_0)
KeyMapper.set(49, KEYS.KEY_1)
KeyMapper.set(50, KEYS.KEY_2)
KeyMapper.set(51, KEYS.KEY_3)
KeyMapper.set(52, KEYS.KEY_4)
KeyMapper.set(53, KEYS.KEY_5)
KeyMapper.set(54, KEYS.KEY_6)
KeyMapper.set(55, KEYS.KEY_7)
KeyMapper.set(56, KEYS.KEY_8)
KeyMapper.set(57, KEYS.KEY_9)


export default KeyMapper;